# Generated by Django 6.0.4 on 2026-04-25 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_rename_rank_movie_ranking_rename_title_movie_titulo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='imdb_id',
        ),
    ]
