# Generated by Django 6.0.4 on 2026-04-25 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_remove_movie_imdb_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='duracao',
        ),
        migrations.AddField(
            model_name='movie',
            name='duracao_minutos',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
