# Generated by Django 6.0.4 on 2026-04-25 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_aiinsight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aiinsight',
            old_name='instrucao',
            new_name='introducao',
        ),
    ]
